services:
  jazzy-base:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: kkhadka343/jazzy-base:latest
    container_name: jazzy-base

    network_mode: host
    stdin_open: true
    tty: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - XDG_RUNTIME_DIR=/tmp/runtime-root

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/dri
